# Form implementation generated from reading ui file '.\\templates\\dlgAbout.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgAbout(object):
    def setupUi(self, dlgAbout):
        dlgAbout.setObjectName("dlgAbout")
        dlgAbout.resize(400, 300)
        dlgAbout.setMinimumSize(QtCore.QSize(400, 300))
        dlgAbout.setMaximumSize(QtCore.QSize(400, 300))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\\\templates\\../img/iconoInmo.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        dlgAbout.setWindowIcon(icon)
        dlgAbout.setModal(True)
        self.frame = QtWidgets.QFrame(parent=dlgAbout)
        self.frame.setGeometry(QtCore.QRect(10, 40, 381, 191))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(130, 20, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lblicono = QtWidgets.QLabel(parent=self.frame)
        self.lblicono.setGeometry(QtCore.QRect(30, 60, 60, 61))
        self.lblicono.setMinimumSize(QtCore.QSize(60, 60))
        self.lblicono.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lblicono.setText("")
        self.lblicono.setPixmap(QtGui.QPixmap(".\\\\templates\\../img/iconoInmo.ico"))
        self.lblicono.setScaledContents(True)
        self.lblicono.setObjectName("lblicono")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setGeometry(QtCore.QRect(130, 50, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.frame)
        self.label_3.setGeometry(QtCore.QRect(130, 80, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.frame)
        self.label_4.setGeometry(QtCore.QRect(130, 110, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.frame)
        self.label_5.setGeometry(QtCore.QRect(130, 140, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setOpenExternalLinks(True)
        self.label_5.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.TextBrowserInteraction)
        self.label_5.setObjectName("label_5")
        self.btnAceptarabout = QtWidgets.QPushButton(parent=dlgAbout)
        self.btnAceptarabout.setGeometry(QtCore.QRect(290, 250, 80, 23))
        self.btnAceptarabout.setMaximumSize(QtCore.QSize(80, 25))
        self.btnAceptarabout.setObjectName("btnAceptarabout")

        self.retranslateUi(dlgAbout)
        QtCore.QMetaObject.connectSlotsByName(dlgAbout)

    def retranslateUi(self, dlgAbout):
        _translate = QtCore.QCoreApplication.translate
        dlgAbout.setWindowTitle(_translate("dlgAbout", "Acerca de:"))
        self.label.setText(_translate("dlgAbout", "Inmo Teis  (By Jorge de Haz)"))
        self.label_2.setText(_translate("dlgAbout", "Autor: Jorge De Haz Martínez"))
        self.label_3.setText(_translate("dlgAbout", "Runetime Version : 0.0.1"))
        self.label_4.setText(_translate("dlgAbout", "Copyright © [1998-2024] Inmoteis&Co"))
        self.label_5.setText(_translate("dlgAbout", "<a href=\"http://www.edu.xunta.gal/centros/iesteis\">Inmo Teis</a>"))
        self.btnAceptarabout.setText(_translate("dlgAbout", "Aceptar"))
