# Form implementation generated from reading ui file '.\\templates\\dlgBuscaProp.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgBuscaProp(object):
    def setupUi(self, dlgBuscaProp):
        dlgBuscaProp.setObjectName("dlgBuscaProp")
        dlgBuscaProp.resize(400, 300)
        dlgBuscaProp.setMinimumSize(QtCore.QSize(300, 300))
        dlgBuscaProp.setSizeIncrement(QtCore.QSize(300, 400))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\\\templates\\../img/iconoInmo.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        dlgBuscaProp.setWindowIcon(icon)
        dlgBuscaProp.setModal(True)
        self.layoutWidget = QtWidgets.QWidget(parent=dlgBuscaProp)
        self.layoutWidget.setGeometry(QtCore.QRect(90, 60, 228, 165))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout.setSpacing(30)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.cmbLocalidad = QtWidgets.QComboBox(parent=self.layoutWidget)
        self.cmbLocalidad.setEditable(True)
        self.cmbLocalidad.setObjectName("cmbLocalidad")
        self.verticalLayout.addWidget(self.cmbLocalidad)
        self.btnAceptarLocalidad = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.btnAceptarLocalidad.setObjectName("btnAceptarLocalidad")
        self.verticalLayout.addWidget(self.btnAceptarLocalidad)

        self.retranslateUi(dlgBuscaProp)
        QtCore.QMetaObject.connectSlotsByName(dlgBuscaProp)

    def retranslateUi(self, dlgBuscaProp):
        _translate = QtCore.QCoreApplication.translate
        dlgBuscaProp.setWindowTitle(_translate("dlgBuscaProp", "Buscar Propiedad"))
        self.label.setText(_translate("dlgBuscaProp", "Elija Localidad de las Propiedades"))
        self.btnAceptarLocalidad.setText(_translate("dlgBuscaProp", "Aceptar"))
