# Form implementation generated from reading ui file '.\\templates\\dlgGestion.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgTipoprop(object):
    def setupUi(self, dlgTipoprop):
        dlgTipoprop.setObjectName("dlgTipoprop")
        dlgTipoprop.resize(400, 300)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\\\templates\\../img/iconoInmo.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        dlgTipoprop.setWindowIcon(icon)
        self.widget = QtWidgets.QWidget(parent=dlgTipoprop)
        self.widget.setGeometry(QtCore.QRect(30, 30, 351, 241))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(parent=self.widget)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(20, 30, 311, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.txtGestipoprop = QtWidgets.QLineEdit(parent=self.frame)
        self.txtGestipoprop.setGeometry(QtCore.QRect(100, 70, 150, 20))
        self.txtGestipoprop.setMinimumSize(QtCore.QSize(150, 20))
        self.txtGestipoprop.setMaximumSize(QtCore.QSize(150, 20))
        self.txtGestipoprop.setObjectName("txtGestipoprop")
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnAltaprop = QtWidgets.QPushButton(parent=self.widget)
        self.btnAltaprop.setMaximumSize(QtCore.QSize(80, 25))
        self.btnAltaprop.setObjectName("btnAltaprop")
        self.horizontalLayout.addWidget(self.btnAltaprop)
        self.btnDeltipoprop = QtWidgets.QPushButton(parent=self.widget)
        self.btnDeltipoprop.setMaximumSize(QtCore.QSize(80, 25))
        self.btnDeltipoprop.setObjectName("btnDeltipoprop")
        self.horizontalLayout.addWidget(self.btnDeltipoprop)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)

        self.retranslateUi(dlgTipoprop)
        QtCore.QMetaObject.connectSlotsByName(dlgTipoprop)

    def retranslateUi(self, dlgTipoprop):
        _translate = QtCore.QCoreApplication.translate
        dlgTipoprop.setWindowTitle(_translate("dlgTipoprop", "Gestión Tipo Propiedades"))
        self.label.setText(_translate("dlgTipoprop", "Introduzca tipo de propiedad a crear o eliminar"))
        self.btnAltaprop.setText(_translate("dlgTipoprop", "Alta"))
        self.btnDeltipoprop.setText(_translate("dlgTipoprop", "Eliminar"))
