# Form implementation generated from reading ui file '.\\templates\\dlgGestion.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgTipoprop(object):
    def setupUi(self, dlgTipoprop):
        dlgTipoprop.setObjectName("dlgTipoprop")
        dlgTipoprop.resize(400, 300)
        dlgTipoprop.setMinimumSize(QtCore.QSize(400, 300))
        dlgTipoprop.setMaximumSize(QtCore.QSize(400, 300))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\\\templates\\../img/iconoInmo.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        dlgTipoprop.setWindowIcon(icon)
        dlgTipoprop.setModal(True)
        self.frame = QtWidgets.QFrame(parent=dlgTipoprop)
        self.frame.setGeometry(QtCore.QRect(31, 31, 349, 181))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(40, 30, 311, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.txtGestipoprop = QtWidgets.QLineEdit(parent=self.frame)
        self.txtGestipoprop.setGeometry(QtCore.QRect(100, 70, 150, 20))
        self.txtGestipoprop.setMinimumSize(QtCore.QSize(150, 20))
        self.txtGestipoprop.setMaximumSize(QtCore.QSize(150, 20))
        self.txtGestipoprop.setObjectName("txtGestipoprop")
        self.lblicono = QtWidgets.QLabel(parent=self.frame)
        self.lblicono.setGeometry(QtCore.QRect(140, 110, 60, 61))
        self.lblicono.setMinimumSize(QtCore.QSize(60, 60))
        self.lblicono.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lblicono.setText("")
        self.lblicono.setPixmap(QtGui.QPixmap(".\\\\templates\\../img/iconoInmo.ico"))
        self.lblicono.setScaledContents(True)
        self.lblicono.setObjectName("lblicono")
        self.layoutWidget = QtWidgets.QWidget(parent=dlgTipoprop)
        self.layoutWidget.setGeometry(QtCore.QRect(80, 230, 250, 25))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnAltaprop = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.btnAltaprop.setMaximumSize(QtCore.QSize(80, 25))
        self.btnAltaprop.setObjectName("btnAltaprop")
        self.horizontalLayout.addWidget(self.btnAltaprop)
        self.btnDeltipoprop = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.btnDeltipoprop.setMaximumSize(QtCore.QSize(80, 25))
        self.btnDeltipoprop.setObjectName("btnDeltipoprop")
        self.horizontalLayout.addWidget(self.btnDeltipoprop)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)

        self.retranslateUi(dlgTipoprop)
        QtCore.QMetaObject.connectSlotsByName(dlgTipoprop)

    def retranslateUi(self, dlgTipoprop):
        _translate = QtCore.QCoreApplication.translate
        dlgTipoprop.setWindowTitle(_translate("dlgTipoprop", "Gestión Tipo Propiedades"))
        self.label.setText(_translate("dlgTipoprop", "Introduzca tipo de propiedad a crear o eliminar"))
        self.btnAltaprop.setText(_translate("dlgTipoprop", "Alta"))
        self.btnDeltipoprop.setText(_translate("dlgTipoprop", "Eliminar"))
